//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweety.Common.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sweety.Common.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string the_stream_does_not_support_read_operations {
            get {
                return ResourceManager.GetString("the stream does not support read operations", resourceCulture);
            }
        }
        
        internal static string the_stream_does_not_support_write_operations {
            get {
                return ResourceManager.GetString("the stream does not support write operations", resourceCulture);
            }
        }
        
        internal static string the_specified_key_size_is_invalid_for_this_algorithm {
            get {
                return ResourceManager.GetString("the specified key size is invalid for this algorithm", resourceCulture);
            }
        }
        
        internal static string the_specified_initialization_vector_does_not_match_the_block_size_of_this_algorithm {
            get {
                return ResourceManager.GetString("the specified initialization vector does not match the block size of this algorit" +
                        "hm", resourceCulture);
            }
        }
        
        internal static string unknown_encryption_cipher_mode {
            get {
                return ResourceManager.GetString("unknown encryption cipher mode", resourceCulture);
            }
        }
        
        internal static string unknown_data_block_padding_mode {
            get {
                return ResourceManager.GetString("unknown data block padding mode", resourceCulture);
            }
        }
        
        internal static string the_plaintext_cannot_be_empty {
            get {
                return ResourceManager.GetString("the plaintext cannot be empty", resourceCulture);
            }
        }
        
        internal static string the_ciphertext_cannot_be_empty {
            get {
                return ResourceManager.GetString("the ciphertext cannot be empty", resourceCulture);
            }
        }
        
        internal static string please_specify_the_main_database_connection_string {
            get {
                return ResourceManager.GetString("please specify the main database connection string", resourceCulture);
            }
        }
        
        internal static string the_connection_string_of_the_slave_database_is_not_specified {
            get {
                return ResourceManager.GetString("the connection string of the slave database is not specified", resourceCulture);
            }
        }
        
        internal static string the_byte_length_of_the_compared_strings_must_not_be_less_than_zero {
            get {
                return ResourceManager.GetString("the byte length of the compared strings must not be less than zero", resourceCulture);
            }
        }
        
        internal static string the_length_of_the_string_to_be_appended_to_the_end_exceeds_the_length_to_be_intercepted_or_equal_to_the_length_to_be_intercepted {
            get {
                return ResourceManager.GetString("the length of the string to be appended to the end exceeds the length to be inter" +
                        "cepted or equal to the length to be intercepted", resourceCulture);
            }
        }
        
        internal static string the_length_of_bytes_after_the_intercepted_string_plus_the_appended_string_exceeds_the_expected_length {
            get {
                return ResourceManager.GetString("the length of bytes after the intercepted string plus the appended string exceeds" +
                        " the expected length", resourceCulture);
            }
        }
        
        internal static string the_length_of_the_hexadecimal_string_should_be_an_even_number {
            get {
                return ResourceManager.GetString("the length of the hexadecimal string should be an even number", resourceCulture);
            }
        }
        
        internal static string the_read_only_collection_cannot_be_modified {
            get {
                return ResourceManager.GetString("the read-only collection cannot be modified", resourceCulture);
            }
        }
        
        internal static string the_starting_index_must_be_greater_than_or_equal_to_zero {
            get {
                return ResourceManager.GetString("the starting index must be greater than or equal to zero", resourceCulture);
            }
        }
        
        internal static string the_length_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the length must be greater than zero", resourceCulture);
            }
        }
        
        internal static string the_starting_index_is_not_in_the_valid_range {
            get {
                return ResourceManager.GetString("the starting index is not in the valid range", resourceCulture);
            }
        }
        
        internal static string the_page_number_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the page number must be greater than zero", resourceCulture);
            }
        }
        
        internal static string the_page_size_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the page size must be greater than zero", resourceCulture);
            }
        }
        
        internal static string the_database_connection_string_cannot_be_null_or_empty {
            get {
                return ResourceManager.GetString("the database connection string cannot be null or empty", resourceCulture);
            }
        }
        
        internal static string the_transaction_was_rollbacked_or_commited__please_provide_an_open_transaction {
            get {
                return ResourceManager.GetString("the transaction was rollbacked or commited, please provide an open transaction", resourceCulture);
            }
        }
        
        internal static string the_database_connection_provided_and_the_database_connection_used_by_the_transaction_must_be_the_same_instance {
            get {
                return ResourceManager.GetString("the database connection provided and the database connection used by the transact" +
                        "ion must be the same instance", resourceCulture);
            }
        }
        
        internal static string the_value_XXX_of_type_XXXType_cannot_be_converted_to_a_value_of_type_IPAddressType {
            get {
                return ResourceManager.GetString("the value XXX of type XXXType cannot be converted to a value of type IPAddressTyp" +
                        "e", resourceCulture);
            }
        }
        
        internal static string the_XXX_property_of_the_encryption_algorithm_instance_contains_XXX_elements__not_just_one_element {
            get {
                return ResourceManager.GetString("the XXX property of the encryption algorithm instance contains XXX elements, not " +
                        "just one element", resourceCulture);
            }
        }
        
        internal static string the_element_of_the_master_database_connection_string_index_XXX_is_a_null_or_empty_string {
            get {
                return ResourceManager.GetString("the element of the master database connection string index XXX is a null or empty" +
                        " string", resourceCulture);
            }
        }
        
        internal static string the_element_of_the_slave_database_connection_string_index_XXX_is_a_null_or_empty_string {
            get {
                return ResourceManager.GetString("the element of the slave database connection string index XXX is a null or empty " +
                        "string", resourceCulture);
            }
        }
        
        internal static string please_call_the_static_method_XXX_to_initialize_before_constructing_the_instance {
            get {
                return ResourceManager.GetString("please call the static method XXX to initialize before constructing the instance", resourceCulture);
            }
        }
        
        internal static string the_value_of_the_property_XXX_is_invalid {
            get {
                return ResourceManager.GetString("the value of the property XXX is invalid", resourceCulture);
            }
        }
        
        internal static string the_value_ranges_from_XXX_to_XXX {
            get {
                return ResourceManager.GetString("the value ranges from XXX to XXX", resourceCulture);
            }
        }
        
        internal static string the_value_ranges_from_XXX_to_XXX_milliseconds {
            get {
                return ResourceManager.GetString("the value ranges from XXX to XXX milliseconds", resourceCulture);
            }
        }
        
        internal static string invalid_character_XXX {
            get {
                return ResourceManager.GetString("invalid character XXX", resourceCulture);
            }
        }
        
        internal static string at_least_XXX_bytes {
            get {
                return ResourceManager.GetString("at least XXX bytes", resourceCulture);
            }
        }
        
        internal static string this_instance_only_accepts_database_connection_objects_of_type_XXX {
            get {
                return ResourceManager.GetString("this instance only accepts database connection objects of type XXX", resourceCulture);
            }
        }
        
        internal static string this_instance_only_accepts_transaction_objects_of_type_XXX {
            get {
                return ResourceManager.GetString("this instance only accepts transaction objects of type XXX", resourceCulture);
            }
        }
    }
}
