//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweety.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sweety.Common.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments {0} and {1} cannot be null at the same time. 的本地化字符串。
        /// </summary>
        internal static string arguments_X_and_Y_cannot_be_null_at_the_same_time {
            get {
                return ResourceManager.GetString("arguments X and Y cannot be null at the same time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least {0} bytes. 的本地化字符串。
        /// </summary>
        internal static string at_least_XXX_bytes {
            get {
                return ResourceManager.GetString("at least XXX bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid character &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string invalid_character_XXX {
            get {
                return ResourceManager.GetString("invalid character XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string invalid_value_XXX {
            get {
                return ResourceManager.GetString("invalid value XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please call the static method {0} to initialize before constructing the instance. 的本地化字符串。
        /// </summary>
        internal static string please_call_the_static_method_XXX_to_initialize_before_constructing_the_instance {
            get {
                return ResourceManager.GetString("please call the static method XXX to initialize before constructing the instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify the main database connection string. 的本地化字符串。
        /// </summary>
        internal static string please_specify_the_main_database_connection_string {
            get {
                return ResourceManager.GetString("please specify the main database connection string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The byte length of the compared strings must not be less than zero. 的本地化字符串。
        /// </summary>
        internal static string the_byte_length_of_the_compared_strings_must_not_be_less_than_zero {
            get {
                return ResourceManager.GetString("the byte length of the compared strings must not be less than zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ciphertext cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string the_ciphertext_cannot_be_empty {
            get {
                return ResourceManager.GetString("the ciphertext cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection string of the slave database is not specified. 的本地化字符串。
        /// </summary>
        internal static string the_connection_string_of_the_slave_database_is_not_specified {
            get {
                return ResourceManager.GetString("the connection string of the slave database is not specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database connection provided and the database connection used by the transaction must be the same instance. 的本地化字符串。
        /// </summary>
        internal static string the_database_connection_provided_and_the_database_connection_used_by_the_transaction_must_be_the_same_instance {
            get {
                return ResourceManager.GetString("the database connection provided and the database connection used by the transact" +
                        "ion must be the same instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database connection string cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string the_database_connection_string_cannot_be_null_or_empty {
            get {
                return ResourceManager.GetString("the database connection string cannot be null or empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element of the master database connection string index [{0}] is a null or empty string. 的本地化字符串。
        /// </summary>
        internal static string the_element_of_the_master_database_connection_string_index_XXX_is_a_null_or_empty_string {
            get {
                return ResourceManager.GetString("the element of the master database connection string index XXX is a null or empty" +
                        " string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element of the slave database connection string index [{0}] is a null or empty string. 的本地化字符串。
        /// </summary>
        internal static string the_element_of_the_slave_database_connection_string_index_XXX_is_a_null_or_empty_string {
            get {
                return ResourceManager.GetString("the element of the slave database connection string index XXX is a null or empty " +
                        "string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string the_length_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the length must be greater than zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of bytes after the intercepted string plus the appended string exceeds the expected length. 的本地化字符串。
        /// </summary>
        internal static string the_length_of_bytes_after_the_intercepted_string_plus_the_appended_string_exceeds_the_expected_length {
            get {
                return ResourceManager.GetString("the length of bytes after the intercepted string plus the appended string exceeds" +
                        " the expected length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of the hexadecimal string should be an even number. 的本地化字符串。
        /// </summary>
        internal static string the_length_of_the_hexadecimal_string_should_be_an_even_number {
            get {
                return ResourceManager.GetString("the length of the hexadecimal string should be an even number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of the string to be appended to the end exceeds the length to be intercepted or equal to the length to be intercepted. 的本地化字符串。
        /// </summary>
        internal static string the_length_of_the_string_to_be_appended_to_the_end_exceeds_the_length_to_be_intercepted_or_equal_to_the_length_to_be_intercepted {
            get {
                return ResourceManager.GetString("the length of the string to be appended to the end exceeds the length to be inter" +
                        "cepted or equal to the length to be intercepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The page number must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string the_page_number_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the page number must be greater than zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The page size must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string the_page_size_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("the page size must be greater than zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The plaintext cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string the_plaintext_cannot_be_empty {
            get {
                return ResourceManager.GetString("the plaintext cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The read-only collection cannot be modified. 的本地化字符串。
        /// </summary>
        internal static string the_read_only_collection_cannot_be_modified {
            get {
                return ResourceManager.GetString("the read-only collection cannot be modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified initialization vector does not match the block size of this algorithm. 的本地化字符串。
        /// </summary>
        internal static string the_specified_initialization_vector_does_not_match_the_block_size_of_this_algorithm {
            get {
                return ResourceManager.GetString("the specified initialization vector does not match the block size of this algorit" +
                        "hm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified key size is invalid for this algorithm. 的本地化字符串。
        /// </summary>
        internal static string the_specified_key_size_is_invalid_for_this_algorithm {
            get {
                return ResourceManager.GetString("the specified key size is invalid for this algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The starting index is not in the valid range. 的本地化字符串。
        /// </summary>
        internal static string the_starting_index_is_not_in_the_valid_range {
            get {
                return ResourceManager.GetString("the starting index is not in the valid range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The starting index must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string the_starting_index_must_be_greater_than_or_equal_to_zero {
            get {
                return ResourceManager.GetString("the starting index must be greater than or equal to zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream does not support read operations. 的本地化字符串。
        /// </summary>
        internal static string the_stream_does_not_support_read_operations {
            get {
                return ResourceManager.GetString("the stream does not support read operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream does not support write operations. 的本地化字符串。
        /// </summary>
        internal static string the_stream_does_not_support_write_operations {
            get {
                return ResourceManager.GetString("the stream does not support write operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction was rollbacked or commited, please provide an open transaction. 的本地化字符串。
        /// </summary>
        internal static string the_transaction_was_rollbacked_or_commited__please_provide_an_open_transaction {
            get {
                return ResourceManager.GetString("the transaction was rollbacked or commited, please provide an open transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of the property {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string the_value_of_the_property_XXX_is_invalid {
            get {
                return ResourceManager.GetString("the value of the property XXX is invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value ranges from {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string the_value_ranges_from_XXX_to_XXX {
            get {
                return ResourceManager.GetString("the value ranges from XXX to XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value ranges from {0} to {1} milliseconds. 的本地化字符串。
        /// </summary>
        internal static string the_value_ranges_from_XXX_to_XXX_milliseconds {
            get {
                return ResourceManager.GetString("the value ranges from XXX to XXX milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &quot;{0}&quot; of type {1} cannot be converted to a value of type {2}. 的本地化字符串。
        /// </summary>
        internal static string the_value_XXX_of_type_XXXType_cannot_be_converted_to_a_value_of_type_IPAddressType {
            get {
                return ResourceManager.GetString("the value XXX of type XXXType cannot be converted to a value of type IPAddressTyp" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} property of the encryption algorithm instance contains {1} elements, not just one element. 的本地化字符串。
        /// </summary>
        internal static string the_XXX_property_of_the_encryption_algorithm_instance_contains_XXX_elements__not_just_one_element {
            get {
                return ResourceManager.GetString("the XXX property of the encryption algorithm instance contains XXX elements, not " +
                        "just one element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This instance only accepts database connection objects of type {0}. 的本地化字符串。
        /// </summary>
        internal static string this_instance_only_accepts_database_connection_objects_of_type_XXX {
            get {
                return ResourceManager.GetString("this instance only accepts database connection objects of type XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This instance only accepts transaction objects of type {0}. 的本地化字符串。
        /// </summary>
        internal static string this_instance_only_accepts_transaction_objects_of_type_XXX {
            get {
                return ResourceManager.GetString("this instance only accepts transaction objects of type XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown data block padding mode. 的本地化字符串。
        /// </summary>
        internal static string unknown_data_block_padding_mode {
            get {
                return ResourceManager.GetString("unknown data block padding mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown encryption cipher mode. 的本地化字符串。
        /// </summary>
        internal static string unknown_encryption_cipher_mode {
            get {
                return ResourceManager.GetString("unknown encryption cipher mode", resourceCulture);
            }
        }
    }
}
